UTIProcessual/Controllers/ProcessosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography.X509Certificates;
using UTIProcessual.Data;
using UTIProcessual.Models;
using UTIProcessual.Models.Cadastro;

namespace UTIProcessual.Controllers
{
    public class ProcessosController : Controller
    {
        private readonly MVCDbContext dbContext;
        public ProcessosController(MVCDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> ListarProcessos()
        {
            var listarProcessos = await dbContext.CadastroProcessos.ToListAsync();
            return View(listarProcessos);
        }


        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adicionar(NovoProcessoViewModel dadosNovoProcessoRequest)
        {
            var processos = new NovoProcesso()
            {
                Id = Guid.NewGuid(),
                NumeroProcessoPenal = dadosNovoProcessoRequest.NumeroProcessoPenal,
                TipoPenal = dadosNovoProcessoRequest.TipoPenal,
                LocalDoCrime = dadosNovoProcessoRequest.LocalDoCrime,
                DataDoCrime = dadosNovoProcessoRequest.DataDoCrime,
                NumeroPCNET = dadosNovoProcessoRequest.NumeroPCNET,
                NumeroREDS = dadosNovoProcessoRequest.NumeroREDS,
                NumInqueritoPolicial = dadosNovoProcessoRequest.NumInqueritoPolicial,

                NomeReu = dadosNovoProcessoRequest.NomeReu,
                FiliacaoReu = dadosNovoProcessoRequest.FiliacaoReu,
                DataNascReu = dadosNovoProcessoRequest.DataNascReu,
                NaturalidadeReu = dadosNovoProcessoRequest.NaturalidadeReu,
                EnderecoReu = dadosNovoProcessoRequest.EnderecoReu,
                TelefoneReu = dadosNovoProcessoRequest.TelefoneReu,

                Advogado = dadosNovoProcessoRequest.Advogado,
                OABAdvogado = dadosNovoProcessoRequest.OABAdvogado,
                DefensoriaPublica = dadosNovoProcessoRequest.DefensoriaPublica
            };

            await dbContext.CadastroProcessos.AddAsync(processos);
            await dbContext.SaveChangesAsync();
            return RedirectToAction("ListarProcessos");
        }


        [HttpGet]
        public async Task <IActionResult> View(Guid id)
        {
            var verProcesso = await dbContext.CadastroProcessos.FirstOrDefaultAsync(x => x.Id == id);

            if (verProcesso != null)
            {
                var viewModel = new EditarProcessoViewModel()
                {
                    Id = verProcesso.Id,
                    NumeroProcessoPenal = verProcesso.NumeroProcessoPenal,
                    TipoPenal = verProcesso.TipoPenal,
                    LocalDoCrime = verProcesso.LocalDoCrime,
                    DataDoCrime = verProcesso.DataDoCrime,
                    NumeroPCNET = verProcesso.NumeroPCNET,
                    NumeroREDS = verProcesso.NumeroREDS,
                    NumInqueritoPolicial = verProcesso.NumInqueritoPolicial,

                    NomeReu = verProcesso.NomeReu,
                    FiliacaoReu = verProcesso.FiliacaoReu,
                    DataNascReu = verProcesso.DataNascReu,
                    NaturalidadeReu = verProcesso.NaturalidadeReu,
                    EnderecoReu = verProcesso.EnderecoReu,
                    TelefoneReu = verProcesso.TelefoneReu,

                    Advogado = verProcesso.Advogado,
                    OABAdvogado = verProcesso.OABAdvogado,
                    DefensoriaPublica = verProcesso.DefensoriaPublica
                };

                return await Task.Run(() => View("View", viewModel));
            }

            return RedirectToAction("View");
        }

        [HttpPost]
        public async Task<IActionResult> View(EditarProcessoViewModel model)
        {
            var verProcesso = await dbContext.CadastroProcessos.FindAsync(model.Id);

            if (verProcesso != null)
            {
                verProcesso.Id = model.Id;
                verProcesso.NumeroProcessoPenal = model.NumeroProcessoPenal;
                verProcesso.TipoPenal = model.TipoPenal;
                verProcesso.LocalDoCrime = model.LocalDoCrime;
                verProcesso.DataDoCrime = model.DataDoCrime;
                verProcesso.NumeroPCNET = model.NumeroPCNET;
                verProcesso.NumeroREDS = model.NumeroREDS;
                verProcesso.NumInqueritoPolicial = model.NumInqueritoPolicial;

                verProcesso.NomeReu = model.NomeReu;
                verProcesso.FiliacaoReu = model.FiliacaoReu;
                verProcesso.DataNascReu = model.DataNascReu;
                verProcesso.NaturalidadeReu = model.NaturalidadeReu;
                verProcesso.EnderecoReu = model.EnderecoReu;
                verProcesso.TelefoneReu = model.TelefoneReu;

                verProcesso.Advogado = model.Advogado;
                verProcesso.OABAdvogado = model.OABAdvogado;
                verProcesso.DefensoriaPublica = model.DefensoriaPublica;

                await dbContext.SaveChangesAsync();

                return RedirectToAction("ListarProcessos");
            }

            return RedirectToAction("ListarProcessos");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditarProcessoViewModel model)
        {
            var excluirProcesso = await dbContext.CadastroProcessos.FindAsync(model.Id);

            if (excluirProcesso != null)
            {
                dbContext.CadastroProcessos.Remove(excluirProcesso);
                await dbContext.SaveChangesAsync();

                return RedirectToAction("ListarProcessos");
            }

            return RedirectToAction("ListarProcessos");
        }

    }
}

UTIProcessual/Views/Processos/Adicionar.cshtml
@model UTIProcessual.Models.NovoProcessoViewModel

@{
}

<h1>Adicionar processo</h1>

<form method="post" action="Adicionar" class="mt-5">
    <fieldset>
        <legend>1) Informações do processo</legend>
        <div class="mb-3">
            <label for="" class="form-label">Número do processo penal</label>
            <input type="number" class="form-control" asp-for="NumeroProcessoPenal">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Tipo Penal</label>
            <input type="text" class="form-control" asp-for="TipoPenal">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>2) Dados do crime</legend>
        <div class="mb-3">
            <label for="" class="form-label">Local do crime</label>
            <input type="text" class="form-control" asp-for="LocalDoCrime">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Data do crime</label>
            <input type="date" class="form-control" asp-for="DataDoCrime">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº PCNET</label>
            <input type="number" class="form-control" asp-for="NumeroPCNET">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº REDS</label>
            <input type="number" class="form-control" asp-for="NumeroREDS">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº Inquérito Policial</label>
            <input type="number" class="form-control" asp-for="NumInqueritoPolicial">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>3) Dados do réu</legend>
        <div class="mb-3">
            <label for="" class="form-label">Nome da pessoa</label>
            <input type="text" class="form-control" asp-for="NomeReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Filiação</label>
            <input type="text" class="form-control" asp-for="FiliacaoReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Data de Nascimento</label>
            <input type="date" class="form-control" asp-for="DataNascReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Naturalidade</label>
            <input type="text" class="form-control" asp-for="NaturalidadeReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Endereço</label>
            <input type="text" class="form-control" asp-for="EnderecoReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Telefone</label>
            <input type="tel" class="form-control" asp-for="TelefoneReu">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>4) Defesa da pessoa acusada</legend>
        <div class="mb-3">
            @*
            <div class="mb-3">
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
                    <label class="form-check-label" for="inlineRadio1">Sim</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
                    <label class="form-check-label" for="inlineRadio2">Não</label>
                </div>
            </div>
            *@

            <div class="mb-3">
                <label for="" class="form-label">Advogada / Advogado</label>
                <input type="text" class="form-control" asp-for="Advogado">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Nº OAB Advogada / Advogado</label>
                <input type="text" class="form-control" asp-for="OABAdvogado">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Defensoria Pública</label>
                <input type="text" class="form-control" asp-for="DefensoriaPublica">
            </div>
        </div>
    </fieldset>

    <button type="submit" class="btn btn-primary">Cadastrar processo</button>
</form>

UTIProcessual/Views/Processos/ListarProcessos.cshtml
@model List<UTIProcessual.Models.Cadastro.NovoProcesso>

@{

}

<h1>Processos</h1>

<table class="table">
    <thead>
        <tr>
            <th>Nº Processo penal</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach (var infoProcesso in Model){
            <tr>
                <td>@infoProcesso.NumeroProcessoPenal</td>
                <td><a href="View/@infoProcesso.Id">Ver processo</a></td>
            </tr>
        }
    </tbody>
</table>

UTIProcessual/Views/Processos/View.cshtml
@model UTIProcessual.Models.EditarProcessoViewModel

@{
}

<h1>Ver processo</h1>

<form method="post" action="View" class="mt-5">
    <fieldset>
        <div class="mb-3">
            <label for="" class="form-label">Id:</label>
            <input type="text" class="form-control" asp-for="Id" readonly>
        </div>

        <legend>1) Informações do processo</legend>
        <div class="mb-3">
            <label for="" class="form-label">Número do processo penal</label>
            <input type="number" class="form-control" asp-for="NumeroProcessoPenal">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Tipo Penal</label>
            <input type="text" class="form-control" asp-for="TipoPenal">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>2) Dados do crime</legend>
        <div class="mb-3">
            <label for="" class="form-label">Local do crime</label>
            <input type="text" class="form-control" asp-for="LocalDoCrime">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Data do crime</label>
            <input type="date" class="form-control" asp-for="DataDoCrime">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº PCNET</label>
            <input type="number" class="form-control" asp-for="NumeroPCNET">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº REDS</label>
            <input type="number" class="form-control" asp-for="NumeroREDS">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Nº Inquérito Policial</label>
            <input type="number" class="form-control" asp-for="NumInqueritoPolicial">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>3) Dados do réu</legend>
        <div class="mb-3">
            <label for="" class="form-label">Nome da pessoa</label>
            <input type="text" class="form-control" asp-for="NomeReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Filiação</label>
            <input type="text" class="form-control" asp-for="FiliacaoReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Data de Nascimento</label>
            <input type="date" class="form-control" asp-for="DataNascReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Naturalidade</label>
            <input type="text" class="form-control" asp-for="NaturalidadeReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Endereço</label>
            <input type="text" class="form-control" asp-for="EnderecoReu">
        </div>
        <div class="mb-3">
            <label for="" class="form-label">Telefone</label>
            <input type="tel" class="form-control" asp-for="TelefoneReu">
        </div>
    </fieldset>

    <br />

    <fieldset>
        <legend>4) Defesa da pessoa acusada</legend>
        <div class="mb-3">
            @*
            <div class="mb-3">
            <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="option1">
            <label class="form-check-label" for="inlineRadio1">Sim</label>
            </div>
            <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="inlineRadioOptions" id="inlineRadio2" value="option2">
            <label class="form-check-label" for="inlineRadio2">Não</label>
            </div>
            </div>
            *@

            <div class="mb-3">
                <label for="" class="form-label">Advogada / Advogado</label>
                <input type="text" class="form-control" asp-for="Advogado">
            </div>

            <div class="mb-3">
                <label for="" class="form-label">Nº OAB Advogada / Advogado</label>
                <input type="text" class="form-control" asp-for="OABAdvogado">
            </div>
            <div class="mb-3">
                <label for="" class="form-label">Defensoria Pública</label>
                <input type="text" class="form-control" asp-for="DefensoriaPublica">
            </div>
        </div>
    </fieldset>

    <button type="submit" class="btn btn-primary">Atualizar dados</button>
    <button type="submit" class="btn btn-danger" asp-action="Delete" asp-controller="Processos">Excluir processo</button>
</form>